### ISSUE TITLE
This might be helpful - Dont appear to Agent

### ISSUE THREAD

**Issue by iwillforce** [znuny/FAQ#1]
Hi there,

I've recently install faq addon for only internal agents purposes. After that, i start to create articles in that, but, for somehow, the "might be useful" widget dont appear me at all. 
https://i.imgur.com/sQ6YKD6.jpg

Im looking for this result:
https://i.imgur.com/t2TEq1M.jpg or this https://i.imgur.com/qhlEzW8.jpg

**Comment by rkaldung** [comment]
Checking the package get this result: this feature is only included for customer user and not for agents. 
It looks like all components are included in the FAQ like Javascript, Templates, etc., and that only the output filter is missing. 
https://github.com/znuny/FAQ/blob/rel-6_0/doc/en/screenshots/ThisMightBeHelpful-Agent-Result.jpg shows how it should look like.

If found a commit related to this: [Added related FAQ article for agents feature. ](https://github.com/znuny/FAQ/commit/51a848714f5f08ac17e2e01860c41dbc9fe65ea5)

**Comment by iwillforce** [comment]
Ok, i see. So, its not possible to get this "sugestions" to my agents for any way?

**Comment by rkaldung** [comment]
> Ok, i see. So, its not possible to get this "sugestions" to my agents for any way?

Let's see if my colleagues create a working output filter for this. Nothing impossible.

**Comment by iwillforce** [comment]
> > Ok, i see. So, its not possible to get this "sugestions" to my agents for any way?
> 
> Let's see if my colleagues create a working output filter for this. Nothing impossible.

Alright!

**Comment by rkaldung** [comment]
@iwillforce I'm back with news: the next release has this feature.

**Comment by rkaldung** [comment]
@iwillforce This feature is now available with version 6.0.30/6.1.1 of the FAQ.
