### ISSUE TITLE
Bug - Different behaviour on input when searching related articles

### ISSUE THREAD

**Issue by rkaldung** [znuny/FAQ#3]
### Expected behavior

When enter data and it is searched for related FAQ articles the search is performed whenever I enter a whitespace.

### Actual behavior

The expected behaviour works only in the text of an article, for the subject I need to loose the focus on the input field.

### How to reproduce

1. Create FAQ entries to search for
2. Click on New Phone Ticket
3. Enter a search term in the text area
4. See the search result
5. Delete the text
6. Enter the same text in the subject **and** and keep the cursor in the field.
7. See that no search is performed
8. Move the cursor out of the subject field
9. See the search result

### Environment

- OS: n.a.
- Browser: Firefox, Safari, Edge
- Framework version 6.0.x / 6.3.x

### Additional information

Agent and customer interface are affected.

**Comment by jepf** [comment]
Internal issue: 9

**Comment by jepf** [comment]
Fixed, will be part of next release for 6.0 and 6.4.
